services:
  - type: web
    name: analyseur-discipline
    env: python
    pythonVersion: "3.10"
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT"
    envVars:
      FLASK_ENV: "production"

